export const THEMES = {
  obsidian: {
    id: 'obsidian',
    name: 'Obsidian',
    graph: {
      background: '#1e1e2e',
      stroke: '#cba6f7',
      strokeWidth: 2.5,
      gridColor: '#313244',
      axisColor: '#6c7086',
      labelColor: '#cdd6f4',
      frameColor: '#45475a',
    },
    ui: {
      '--bg':           '#1a1a2e',
      '--panel':        '#16213e',
      '--surface':      '#1e2040',
      '--border':       '#2a2a5a',
      '--text':         '#e0e0e0',
      '--text-muted':   '#9e9eb8',
      '--accent':       '#a29bfe',
      '--accent-fg':    '#ffffff',
      '--accent-hover': '#6c5ce7',
      '--editor-bg':    '#0d1117',
      '--editor-text':  '#cdd9e5',
      '--error':        '#f38ba8',
      '--code-bg':      '#161b22',
      '--hl-key':       '#82aaff',
      '--hl-prop':      '#c3e88d',
      '--hl-func':      '#c792ea',
      '--hl-var':       '#eeffff',
      '--hl-num':       '#f78c6c',
      '--hl-color-val': '#ffcb6b',
      '--hl-op':        '#89ddff',
    },
  },

  glacier: {
    id: 'glacier',
    name: 'Glacier',
    graph: {
      background: '#f0f4f8',
      stroke: '#2d6a9f',
      strokeWidth: 2.5,
      gridColor: '#c8d8e8',
      axisColor: '#4a6fa5',
      labelColor: '#334e68',
      frameColor: '#b0c4d8',
    },
    ui: {
      '--bg':           '#eef2f7',
      '--panel':        '#ffffff',
      '--surface':      '#f4f7fb',
      '--border':       '#c8d8e8',
      '--text':         '#243447',
      '--text-muted':   '#627d98',
      '--accent':       '#2d6a9f',
      '--accent-fg':    '#ffffff',
      '--accent-hover': '#1a4971',
      '--editor-bg':    '#fafcff',
      '--editor-text':  '#243447',
      '--error':        '#c0392b',
      '--code-bg':      '#f0f4f8',
      '--hl-key':       '#1565c0',
      '--hl-prop':      '#2e7d32',
      '--hl-func':      '#6a1b9a',
      '--hl-var':       '#1a1a1a',
      '--hl-num':       '#e65100',
      '--hl-color-val': '#f57f17',
      '--hl-op':        '#0e7490',
    },
  },

  magma: {
    id: 'magma',
    name: 'Magma',
    graph: {
      background: '#17050b',
      stroke: '#ff6b35',
      strokeWidth: 2.5,
      gridColor: '#2d1008',
      axisColor: '#7a3010',
      labelColor: '#ffd4a8',
      frameColor: '#4a1a08',
    },
    ui: {
      '--bg':           '#17050b',
      '--panel':        '#200a0e',
      '--surface':      '#29100e',
      '--border':       '#3d1810',
      '--text':         '#ffd4a8',
      '--text-muted':   '#c4724a',
      '--accent':       '#ff6b35',
      '--accent-fg':    '#17050b',
      '--accent-hover': '#e55a24',
      '--editor-bg':    '#120407',
      '--editor-text':  '#ffd4a8',
      '--error':        '#ff8a8a',
      '--code-bg':      '#1a0508',
      '--hl-key':       '#82aaff',
      '--hl-prop':      '#c3e88d',
      '--hl-func':      '#ff79c6',
      '--hl-var':       '#f8f8f2',
      '--hl-num':       '#ffb86c',
      '--hl-color-val': '#f1fa8c',
      '--hl-op':        '#ff79c6',
    },
  },

  moonlight: {
    id: 'moonlight',
    name: 'Moonlight',
    graph: {
      background: '#212337',
      stroke: '#82aaff',
      strokeWidth: 2.5,
      gridColor: '#2f3354',
      axisColor: '#444a73',
      labelColor: '#c8d3f5',
      frameColor: '#3d4470',
    },
    ui: {
      '--bg':           '#212337',
      '--panel':        '#1b1d2e',
      '--surface':      '#252740',
      '--border':       '#2f3354',
      '--text':         '#c8d3f5',
      '--text-muted':   '#7a83b3',
      '--accent':       '#82aaff',
      '--accent-fg':    '#1b1d2e',
      '--accent-hover': '#5b8af0',
      '--editor-bg':    '#171828',
      '--editor-text':  '#c8d3f5',
      '--error':        '#ff98a4',
      '--code-bg':      '#1a1c2d',
      '--hl-key':       '#89ddff',
      '--hl-prop':      '#c3e88d',
      '--hl-func':      '#c792ea',
      '--hl-var':       '#eeffff',
      '--hl-num':       '#f78c6c',
      '--hl-color-val': '#ffcb6b',
      '--hl-op':        '#89ddff',
    },
  },
};

export const DEFAULT_THEME = 'obsidian';
